default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: dude
  password: supersecret

development:
  <<: *default
  database: bedrock


test:
  <<: *default
  database: bedrock


production:
  <<: *default
  database: bedrock
